config/routes.rb
Nerdnews::Application.routes.draw do |map|

  match 'toggle_pref/:id' => 'rss_items#toggle_pref', :as  => :toggle_pref

  resources :rss_items

  root :to => "rss_items#index"

end

app/models/rss_item.rb
# == Schema Information
# Schema version: 20090926230647
#
# Table name: rss_items
#
#  id          :integer         not null, primary key
#  source      :string(255)
#  url         :string(255)
#  title       :string(255)
#  description :text
#  post_time   :datetime
#

class RssItem < ActiveRecord::Base
  validates_uniqueness_of :url
  
  # Load our feed_url config
  FEED_YAML = YAML.load_file 'config/feed_urls.yml'
  
  def self.update_feeds
    feeds = {}
    # Populate our feeds[] array with the feeds for each feed_url source
    FEED_YAML["feeds"].each do |feed_name, feed_url|
      feeds[feed_url] = FeedTools::Feed.open(feed_url)
    end
    # Create RssItems from each of our feeds
    feeds.each do |feed_url, feed|
      feed.items.each do |feed_item|
        create(:source => feed_url, :url => feed_item.link, :title => feed_item.title,
               :description => feed_item.description, :post_time => feed_item.time)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
  
  before_filter :check_cookies
  
  def check_cookies
    if cookies[:prefs_set].blank? || cookies[:prefs_set] == {:value => false}
      # This user has never set any preferences, define defaults
      set_preferred_feeds([:slashdot, :digg, :delicious])
    end
  end
  
  private
  def set_preferred_feeds(feed_list=[])
    # Loop through our feed_list and set 
    unless feed_list.blank?
      feed_list.each do |feed|
        cookies[feed] = {:value => true, :expires => 1.year.from_now}
      end
    end
    # Set :prefs_set to true
    cookies[:prefs_set] = {:value => true, :expires => 1.year.from_now}
  end
end

app/controllers/rss_items_controller.rb
class RssItemsController < ApplicationController

  def index
    get_preferred_feeds_from_cookie
    # We only want to get the feeds associated with our preferences
    conditions = ""
    no_preferred_feeds = true # We want to check for people deselecting all feeds
    @preferred_feeds.each do |preferred_feed, setting|
      if setting == 1 || setting == true
        conditions += "source LIKE '" + RssItem::FEED_YAML['feeds'][preferred_feed] + "' OR "
        no_preferred_feeds = false
      end
    end
    conditions.gsub!(/ OR $/, '')
    logger.debug("Our SQL conditions: #{conditions}")
    unless no_preferred_feeds
      @rss_items = RssItem.paginate(:all, :conditions => conditions,
                                    :order => 'post_time DESC', :page => params[:page])
    end
  end

  def toggle_pref
    feed = params[:id]
    logger.debug("#{feed} is currently set to #{cookies[feed]}, which is of type #{cookies[feed].class}")
    # Toggle whether the feed is a preferred feed in our cookie
    cookies[feed] == '1' ? cookies[feed] = 0 : cookies[feed] = 1
    logger.debug("#{feed} is now set to #{cookies[feed]}")
    redirect_to :action => :index
  end
  
  private
  def get_preferred_feeds_from_cookie
    logger.debug("Getting the preferred feeds from the cookie...")
    @preferred_feeds = {}
    RssItem::FEED_YAML['feeds'].each do |feed_name, feed_url|
      if cookies[feed_name].blank?
        @preferred_feeds[feed_name] = 0
      elsif cookies[feed_name] == '0' || cookies[feed_name] == false
        @preferred_feeds[feed_name] = 0
      else
        @preferred_feeds[feed_name] = 1
      end
      logger.debug("preferred_feed setting: #{feed_name} => #{@preferred_feeds[feed_name]}")
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Detect iphone/ipod touch requests
  def iphone_request?
    (agent = request.env["HTTP_USER_AGENT"]) && agent[/(Mobile\/.+Safari)/]
  end
end

app/helpers/rss_items_helper.rb
module RssItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <%= stylesheet_link_tag 'small', :media => "only screen and (max-device-width: 480px)" %>
    <%= stylesheet_link_tag 'application', :media => "screen and (min-device-width: 481px)" %>
    <%= csrf_meta_tag %>
    <title>Nerd news</title>
    <%- if iphone_request? -%>
    <meta name="viewport" content="width=device-width">
    <%- end -%>
  </head>
  <body>
    <div id="site_title">
      <h1>Nerd news</h1>
      <h2>
        <%- @preferred_feeds.each do |feed_name, setting| -%>
          <%- if setting == 1 -%>
            <%= link_to(feed_name.humanize, toggle_pref_path(feed_name)) %>&nbsp;
          <%- else -%>
            <del>
              <%= link_to(feed_name.humanize, toggle_pref_path(feed_name)) %>
            </del>
            &nbsp;
          <%- end -%>
        <%- end -%>
        </h2>
    </div>
  <%= yield %>
  </body>
</html>

app/views/rss_items/index.html.erb
<%- if @rss_items.blank? -%>
  <p>You have deselected all the feed sources, or no feeds exist from the selected source(s)!</p>
<%- else -%>
  <%= will_paginate @rss_items %>
  <% for rss_item in @rss_items -%>
    <div class="rss_item">
      <h1><%= link_to(raw(rss_item.title), rss_item.url) %></h1>
      <div class="post_time">
        Post time: <%= rss_item.post_time.to_s(:long) %>
      </div>
      <div class="description">
        <%= raw(rss_item.description) %>
      </div><!-- END "description" -->
    </div>
  <% end -%>
  <%= will_paginate @rss_items %>
<%- end -%>